#                              ██   █    ██   ▄█▄    █▄▄▄▄ ▄█    ▄▄▄▄▀ ▄▄▄▄▀ ▀▄    ▄ 
#                              █ █  █    █ █  █▀ ▀▄  █  ▄▀ ██ ▀▀▀ █ ▀▀▀ █      █  █  
#                              █▄▄█ █    █▄▄█ █   ▀  █▀▀▌  ██     █     █       ▀█   
#                              █  █ ███▄ █  █ █▄  ▄▀ █  █  ▐█    █     █        █    
#                                 █     ▀   █ ▀███▀    █    ▐   ▀     ▀       ▄▀     
#                                █         █          ▀                              
#                               ▀         ▀                                          

colors.draw_bold_text_with_bright_colors = true
[font]
	size = 16
	normal = { family = "ShureTechMono Nerd Font", style = "Regular"}
	bold = { family = "ShureTechMono Nerd Font", style = "Bold"}
	italic = { family = "ShureTechMono Nerd Font", style = "Italic"}

# Default colors
[colors.primary]
	background = '#000b1e'
	foreground = '#0abdc6'

[colors.cursor]
text   = '#000b1e'
cursor = '#0abdc6'

# Normal colors
[colors.normal]
black   = '#123e7c'
red     = '#ff0000'
green   = '#d300c4'
yellow  = '#f57800'
blue    = '#123e7c'
magenta = '#711c91'
cyan    = '#0abdc6'
white   = '#d7d7d5'

# Bright colors
[colors.bright]
black   = '#1c61c2'
red     = '#ff0000'
green   = '#d300c4'
yellow  = '#f57800'
blue    = '#00ff00'
magenta = '#711c91'
cyan    = '#0abdc6'
white   = '#d7d7d5'
