#! /bin/sh

killall sxhkd &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "Library" floating=on
bspc config normal_border_color "#222222"
bspc config focused_border_color "#ff0000"
#compfy -b
picom -b
kitty &
#polybar &
killall polybar
polybar -c ~/.config/polybar/bar1.ini &
dunst &
wal -i Pictures/wallpapers/ --saturate 0.7 &
xsetroot -name "borderColor #ff0066" &
#/home/bhu2/dev/bin/battery.sh
