effects = smaa:cas:color:deband

casSharpness = 0.25

smaaThreshold = 0.08
smaaMaxSearchSteps = 32
smaaMaxSearchStepsDiag = 16
smaaCornerRounding = 25

casSharpness = 0.15

colorSaturation = 1.1
colorContrast = 1.05

debandIterations = 2
debandThreshold = 0.02
ditherStrength = 0.4
