#! /bin/sh

killall sxhkd &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "Library" floating=on
bspc config normal_border_color "#222222"
bspc config focused_border_color "#ff0000"
#compfy -b
picom -b
redshift -l 12.9716:77.5946 &
alacritty &
polybar &
killall polybar
polybar &
dunst &
wal -i Pictures/wallpapers/ --saturate 0.7 &
xsetroot -name "borderColor #ff0000" &
touchegg &
/home/bhu2/dev/bin/battery.sh
